# !file này thiết lập tự động buil,deploy,build run,tên,run
version: "3.6"

services:
  shop-shoe-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Chat-App
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app/src
    environment:
      NODE_ENV: "development"
    networks:
      - upload-network
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: npm run dev

networks:
  upload-network:
    driver: bridge
